version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/laravel57
hooks:
   AfterInstall:
    - location: scripts/installpackages.sh
      runas: root
    - location: scripts/restartapache.sh
      runas: root
    - location: scripts/permissions.sh
      runas: root
    - location: scripts/restartapache.sh
      runas: root